### ISSUE TITLE
describing the privacy threat of disclosure of use of assistive technology

### ISSUE THREAD

**Issue by npdoty** [w3c/core-aam#155] opened 2022-12-07 02:31 UTC
The Privacy Considerations section notes that there is a potential threat in describing different content to users who are using assistive technology that the author could subsequently observe from their behavior (that you clicked on a particular link, etc.) that a user was likely employing that technology. The text notes this as an active fingerprinting concern. That is possible, it could be an additional bit of potentially identifying information that could be added to a larger fingerprint. 

Is it just using-accessible-technology-or-not, or could this be used to figure out exactly what kind of assistive technology is in use? 

I would emphasize more that it's a potential disclosure of potentially sensitive information about the user (that they may need assistance of a particular kind).

**Comment by cookiecrook** [comment] 2022-12-08 19:22
This particular issue is broader than ARIA, JavaScript itself being the main culprit for privacy risk. The Working Group asked the TAG for guidance on how this affects ARIA, based on the more serious implications in other core web technologies like the JavaScript even model.

Closing as duplicate of https://github.com/w3ctag/design-principles/issues/293

**Closed by cookiecrook** 2022-12-08 19:22 UTC
Labels: privacy-tracker
