### ISSUE TITLE
Should role="complementary" have the same conditional mappings as the corresponding <aside> element?

### ISSUE THREAD

**Issue by sivakusayan** [w3c/core-aam#206] opened 2023-10-26 03:25 UTC
I read through the [`<aside>` conditional mapping PR](https://github.com/w3c/html-aam/pull/350) so I could properly review the [Blink PR implementing it](https://chromium-review.googlesource.com/c/chromium/src/+/4960293). If I'm correctly understanding things, it means that browsers need to make a special distinction between how to map HTML complementary regions and ARIA complementary regions, since ARIA complementary regions are [always `role="complementary"` no matter how they are nested](https://www.w3.org/TR/core-aam-1.2/#role-map-complementary).

Is that extra complexity needed, or would it make sense to simplify things by having the `<aside>` element unconditionally map to `role="complementary"`, and then have a `role="complementary"` element conditionally map to a landmark? I see there is precedent for something similar with the `role="region"` and `role="form"` mappings, although the spec would need to clarify the ARIA equivalent for "sectioning content". 

If it's intended for ARIA and HTML complementary regions to behave differently, then what is the expected behavior when we have an `<aside>` element nested inside an element with `role="region"`? I see that the [test case](https://scottaohara.github.io/testing/aside/) has this HTML:
```
<section role="presentation">
	start of section role=presentation | none
	    <aside class="yes">This aside maps to role=complementary</aside>
	end of section role=presentation | none
</section>
```
In that case, do we only care about the ARIA role when looking at ancestors?

**Comment by scottaohara** [comment] 2023-10-26 10:58
“what is the expected behavior when we have an aside element nested inside an element with role="region"?”

that is an ambiguity in html aam that exists for this element as well as header and footer which I need to correct. 

But to your larger question, the reason aside, header, and footer change their roles is because html’s definition of each element accounts for use cases beyond where their implicit landmark roles are meant to be used.  So the html elements need to be mailable to these use cases.  Declaring ARIA roles is an explicit action taken by the author, so if someone is using role=complementary, then that’s the role they’re intending to use so it should be exposed as such.



(I say this knowing that the wg has also talked about what to do for roles that authors are blatantly misusing - Eg role=listitem that is not an a11y child of a list. But this issue is not in scope of that topic)

**Comment by jnurthen** [comment] 2023-10-26 17:03
Closing based on above discussion and ARIA meeting

**Closed by jnurthen** 2023-10-26 17:03 UTC
